services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7u"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    volumes:
  - /run/user/1000/pulse/native:/run/user/1000/pulse/native
   environment:
  - PULSE_SERVER=unix:/run/user/1000/pulse/native

    restart: always
    stop_grace_period: 2m
